apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
      - name: backend-container
        image: hyungdoyou/be:2.VERSION
        resources:
          requests:
            memory: "1024m"
            cpu: "600m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /product/list/1/1
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /product/list/1/1
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: backend-config
      terminationGracePeriodSeconds: 5